version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/api/occupancy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/api/video"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/vision/processing"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/vision/video_stream"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
