version: '3.8'
services:
  processing_service:
    build: ./services/processing_service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  video_service:
    build: ./services/video_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  occupancy_service:
    build: ./services/occupancy_service
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  auth_service:
    build: ./services/auth_service
    ports:
      - "8003:8003"