version: '3.8'
services:
  video_service:
    build: ./services/video_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  occupancy_service:
    build: ./services/occupancy_service
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  auth_service:
    build: ./services/auth_service
    ports:
      - "8003:8003"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api_gateway:
    image: nginx:latest
    volumes:
      - ./services/api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "443:443"
    depends_on:
      - video_service
      - occupancy_service
      - auth_service
