version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  processing_service:
    build: ./services/processing_service
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  video_service:
    build: ./services/video_service
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  occupancy_service:
    build: ./services/occupancy_service
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  auth_service:
    build: ./services/auth_service
    ports:
      - "8003:8003"
    restart: unless-stopped

  video_stream_service:
    build: ./services/video_stream_service
    ports:
      - "8010:8010"
    environment:
      - VIDEO_PATHS={"entrada1":"resources/parking1.mp4"}
    volumes:
      - ./resources:/app/resources
    depends_on:
      - video_service
      - occupancy_service
      - auth_service
    restart: unless-stopped

  api_gateway:
    image: nginx:latest
    volumes:
      - ./services/api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - video_service
      - occupancy_service
      - auth_service
    restart: unless-stopped

volumes:
  redis_data: